import { createInterface } from "readline";
import { writeFileSync, existsSync } from "fs";
import { resolve } from "path";

const readline = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    readline.question(prompt, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function setup() {
  console.log("=".repeat(60));
  console.log("Tax Advisor Service - Setup Wizard");
  console.log("=".repeat(60));
  console.log();

  const envPath = resolve(process.cwd(), ".env");

  if (existsSync(envPath)) {
    const overwrite = await question(".env file already exists. Overwrite? (y/N): ");
    if (overwrite.toLowerCase() !== "y") {
      console.log("Setup cancelled.");
      readline.close();
      process.exit(0);
    }
  }

  console.log("Please provide the following configuration:\n");

  // Port configuration
  const port = await question("Server port (default: 3000): ");
  const PORT = port || "3000";

  // Anthropic API Key
  console.log("\nAnthropic API Key:");
  console.log("Get your key from: https://console.anthropic.com/");
  const apiKey = await question("ANTHROPIC_API_KEY: ");

  if (!apiKey || !apiKey.startsWith("sk-ant-")) {
    console.error("\n❌ Invalid API key format. Should start with 'sk-ant-'");
    readline.close();
    process.exit(1);
  }

  // CORS configuration
  console.log("\nCORS Configuration:");
  console.log("Enter allowed origins (comma-separated, or * for all)");
  const origins = await question("ALLOWED_ORIGINS (default: *): ");
  const ALLOWED_ORIGINS = origins || "*";

  // MCP Server Path
  console.log("\nMCP Server Configuration:");
  console.log("This service connects to an external MCP server for tax tools.");
  const mcpPath = await question("Path to MCP server entry point (e.g., ../tax-advisor-mcp/dist/index.js): ");

  let MCP_PATH = mcpPath;
  if (mcpPath && !existsSync(resolve(process.cwd(), mcpPath))) {
    console.warn(`⚠️  Warning: Path '${mcpPath}' does not exist`);
    const proceed = await question("Continue anyway? (y/N): ");
    if (proceed.toLowerCase() !== "y") {
      console.log("Setup cancelled.");
      readline.close();
      process.exit(0);
    }
  }

  // MCP Server Type
  console.log("\nMCP Connection Type:");
  console.log("1. stdio (default - communicates via stdin/stdout)");
  console.log("2. http (REST API)");
  const mcpType = await question("Select type (1/2, default: 1): ");
  const MCP_TYPE = mcpType === "2" ? "http" : "stdio";

  // MCP HTTP URL (if applicable)
  let MCP_HTTP_URL = "";
  if (MCP_TYPE === "http") {
    MCP_HTTP_URL = await question("MCP HTTP URL (e.g., http://localhost:3001): ");
  }

  // Claude Model
  console.log("\nClaude Model Configuration:");
  const model = await question("Model (default: claude-sonnet-4-20250514): ");
  const CLAUDE_MODEL = model || "claude-sonnet-4-20250514";

  // Max tokens
  const maxTokens = await question("Max tokens per response (default: 1024): ");
  const MAX_TOKENS = maxTokens || "1024";

  // Generate .env content
  const envContent = `# Tax Advisor Service Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# Server Configuration
PORT=${PORT}

# Anthropic API
ANTHROPIC_API_KEY=${apiKey}

# CORS
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

# MCP Server
MCP_TYPE=${MCP_TYPE}
MCP_PATH=${MCP_PATH}
${MCP_TYPE === "http" ? `MCP_HTTP_URL=${MCP_HTTP_URL}` : "# MCP_HTTP_URL=http://localhost:3001"}

# Claude Configuration
CLAUDE_MODEL=${CLAUDE_MODEL}
MAX_TOKENS=${MAX_TOKENS}
`;

  writeFileSync(envPath, envContent);

  console.log("\n" + "=".repeat(60));
  console.log("✅ Setup complete! Configuration saved to .env");
  console.log("=".repeat(60));
  console.log("\nNext steps:");
  console.log("1. Review your .env file");
  console.log("2. Start development server: npm run dev");
  console.log("3. Or build for production: npm run build && npm start");
  console.log("\nService will be available at: http://localhost:" + PORT);
  console.log();

  // Integration instructions
  console.log("=".repeat(60));
  console.log("📱 INTEGRATION OPTIONS");
  console.log("=".repeat(60));

  console.log("\n🖥️  Option 1: Use with LLM Desktop Apps (Claude Desktop, etc.)");
  console.log("-".repeat(60));
  console.log("You can use this service as an MCP server with Claude Desktop:\n");
  console.log("1. Start this service: npm run dev");
  console.log("2. Open your Claude Desktop config file:");
  console.log("   macOS: ~/Library/Application Support/Claude/claude_desktop_config.json");
  console.log("   Windows: %APPDATA%\\Claude\\claude_desktop_config.json\n");
  console.log("3. Add this configuration:\n");
  console.log('   {');
  console.log('     "mcpServers": {');
  console.log('       "tax-advisor": {');
  console.log('         "command": "node",');
  console.log('         "args": ["' + process.cwd().replace(/\\/g, '/') + '/dist/index.js"],');
  console.log('         "env": {');
  console.log('           "PORT": "' + PORT + '",');
  console.log('           "ANTHROPIC_API_KEY": "' + apiKey + '"');
  console.log('         }');
  console.log('       }');
  console.log('     }');
  console.log('   }\n');
  console.log("4. Restart Claude Desktop");
  console.log("5. The tax advisor tools will be available in Claude!\n");

  console.log("\n🌐 Option 2: Integrate with Next.js Website");
  console.log("-".repeat(60));
  console.log("Use the service in your Next.js application:\n");
  console.log("STEP 1: Install in your Next.js project");
  console.log("   cd your-nextjs-app");
  console.log("   npm install\n");

  console.log("STEP 2: Copy the client SDK");
  console.log("   cp " + process.cwd() + "/client-sdk.ts src/lib/tax-advisor.ts\n");

  console.log("STEP 3: Create an API route (app/api/tax/route.ts):");
  console.log(`
   import { TaxAdvisorClient } from '@/lib/tax-advisor';
   import { NextRequest } from 'next/server';

   const client = new TaxAdvisorClient('http://localhost:${PORT}');

   export async function POST(req: NextRequest) {
     const { message } = await req.json();

     try {
       const response = await client.chat(message);
       return Response.json(response);
     } catch (error) {
       return Response.json(
         { error: 'Failed to get response' },
         { status: 500 }
       );
     }
   }
`);

  console.log("STEP 4: Create a chat component (components/TaxChat.tsx):");
  console.log(`
   'use client';
   import { useState } from 'react';

   export default function TaxChat() {
     const [message, setMessage] = useState('');
     const [response, setResponse] = useState('');

     const sendMessage = async () => {
       const res = await fetch('/api/tax', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json' },
         body: JSON.stringify({ message }),
       });
       const data = await res.json();
       // Extract text from response
       const text = data.response
         .filter(b => b.type === 'text')
         .map(b => b.text)
         .join('\\\\n');
       setResponse(text);
     };

     return (
       <div>
         <input
           value={message}
           onChange={(e) => setMessage(e.target.value)}
           placeholder="Ask about taxes..."
         />
         <button onClick={sendMessage}>Send</button>
         <div>{response}</div>
       </div>
     );
   }
`);

  console.log("STEP 5: Use in your page (app/page.tsx):");
  console.log(`
   import TaxChat from '@/components/TaxChat';

   export default function Home() {
     return <TaxChat />;
   }
`);

  console.log("\nSTEP 6: Update CORS in .env to allow your Next.js app:");
  console.log("   ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000\n");

  console.log("STEP 7: Start both services:");
  console.log("   # Terminal 1 - Tax Advisor Service");
  console.log("   npm run dev");
  console.log("");
  console.log("   # Terminal 2 - Next.js App");
  console.log("   cd your-nextjs-app && npm run dev\n");

  console.log("\n💡 Alternative: Use the HTML widget directly");
  console.log("-".repeat(60));
  console.log("For a quick integration, copy examples/web-integration.html");
  console.log("into your Next.js public/ folder and customize it!\n");

  console.log("=".repeat(60));
  console.log("📚 Documentation");
  console.log("=".repeat(60));
  console.log("- Integration guide: INTEGRATION.md (detailed instructions!)");
  console.log("- Full examples: ./examples/");
  console.log("- API documentation: README.md");
  console.log("- Client SDK docs: client-sdk.ts");
  console.log("\n💡 TIP: Run 'cat INTEGRATION.md' to see full integration docs");
  console.log("=".repeat(60));
  console.log();

  readline.close();
}

setup().catch((error) => {
  console.error("Setup failed:", error);
  readline.close();
  process.exit(1);
});
